#
# This site was originally deployed by Netlify to https://acol.christmind.info. This has changed
# so that it is incorporated into the Netlify site cmi-www and is accessed at
# https://www.christmind.info/t/acol.
#
# This config file is used update the cmi-acol Netlify site with a page that imforms the user
# that the site has moved and to include a _redirects file that will forward references to 
# https://acol.christmind.info to the appropriate destination.
#
# To develop this site
#
# 1. npm run deploy:netlify
# 2. Edit moved.md, _redirects and any other files
# 3. Test locally at localhost:9912
# 4. Use the command line from the project root to deploy to Netlify
#     $ netlify deploy --prod
#
# The switch from https://acol.christmind.info to https://www.christmind.info/t/acol happened
# on March 19, 2019. Maintaining the old Netlify site, cmi-acol, is needed only for a short 
# time.
#
# CMI

sourceId: 14
sid:  "acol"
cmiTitle: "Teachings of Christ Mind"

# Setup
title:        'A Course of Love'
tagline:      ''
description:  ''
url:          'https://acol.christmind.info'
baseurl:      ''
keywords:     "Christ Mind, ACOL"
src-url:      'https://acol.christmind.info'
port:         9914

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown

include: [ _redirects ]

exclude: [
  deploy,
  LICENSE,
  README.md,
  Gemfile,
  Gemfile.lock,
  package.json,
  package-lock.json,
  node_modules,
  webpack.config.js,
  src,
  project,
  _acq,
  _course,
  _dialog,
  _treatise
]


