# CMI
destination: "../cmi-www/t/acol"

sourceId: 14
cmiTitle: "Teachings of Christ Mind"
sid:  "acol"

# Setup
title:        'A Course of Love'
tagline:      ''
description:  ''
url:          'https://www.christmind.info/t/acol'
baseurl:      ''
keywords:     "Christ Mind, ACOL"
src-url:      'https://www.christmind.info/t/acol'
port:         9914

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

fb-appId:     448658485318107

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap

# Collections for transcripts
collections:
  course:
    output: true
    title: "Book One: A Course of Love"
  treatise:
    output: true
    title: "Book Two: The Treatises"
  dialog:
    output: true
    title: "Book Three: The Dialogues"
  acq:
    output: true
    title: "Get Acquainted"

defaults:
  - scope:
      path: ""
      type: course
    values:
      layout: transcript
      book: "Book One"
      image: "/t/acol/public/img/acol/course-big.jpg"
      image-width: 612
      image-height: 792
      bid: "course"
  - scope:
      path: ""
      type: treatise
    values:
      layout: transcript
      book: "Book Two"
      image: "/t/acol/public/img/acol/treatise-big.jpg"
      image-width: 612
      image-height: 792
      bid: "treatise"
  - scope:
      path: ""
      type: dialog
    values:
      layout: transcript
      book: "Book Three"
      image: "/t/acol/public/img/acol/dialog-big.jpg"
      image-width: 612
      image-height: 792
      bid: "dialog"
  - scope:
      path: ""
      type: acq
    values:
      layout: transcript
      book: "Get Acquainted"
      image: "/t/acol/public/img/acol/acq-big.jpg"
      image-width: 612
      image-height: 792
      bid: "acq"

exclude: [
  moved.html, deploy, LICENSE, README.md, Gemfile, Gemfile.lock, package.json, package-lock.json, node_modules, webpack.config.js, src, project
]

